FROM python:3.10.2

RUN apt-get update -y

# python ライブラリのインストール
RUN python -m pip install pandas
RUN python -m pip install numpy
RUN python -m pip install matplotlib
RUN python -m pip install jupyterlab
RUN python -m pip install notebook

RUN apt-get install -y zlib1g-dev libffi-dev libgmp-dev wget opam
RUN apt update -y

# RUN opam init -y &&\
# opam install tuareg ocp-indent utop merlin user-setup -y &&\
# opam user-setup install -y &&\
# eval `opam config env` -y 

# RUN pip install jupyter
# RUN opam install jupyter
# RUN grep topfind ~/.ocamlinit || echo '#use "topfind";;' >> ~/.ocamlinit  # For using '#require' directive
# RUN grep Topfind.log ~/.ocamlinit || echo 'Topfind.log:=ignore;;' >> ~/.ocamlinit  # Suppress logging of topfind (recommended but not necessary)
# RUN ocaml-jupyter-opam-genspec
# RUN jupyter kernelspec install [ --user ] --name "ocaml-jupyter-$(opam var switch)" "$(opam var share)/jupyter"